version: '2'
services:
  web:
    image: ruby:2.4.3
    working_dir: /app
    command: bash
    depends_on:
      - db
    environment:
      BUNDLE_PATH: /bundle
      BUNDLE_SILENCE_ROOT_WARNING: "true"
      HISTFILE: /app/.bash_history
      DATABASE_HOST: db
      DATABASE_USER: postgres
      DATABASE_PASSWORD: postgres
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    volumes_from:
      - bundle

  db:
    image: postgres:alpine
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - '15432:5432'

  bundle:
    image: busybox
    volumes:
      - /bundle
